# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby
    - build

before_script:
  - apt-get update -y
  - 'which ssh-agent || ( apt-get install openssh-client locales rsync -y )'
  - echo "pl_PL UTF-8" > /etc/locale.gen
  - locale-gen pl_PL.UTF-8
  - export LANG=pl_PL.UTF-8
  - export LANGUAGE=pl_PL:en
  - export LC_ALL=pl_PL.UTF-8
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ruby -v
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor


middleman:
  script:
  - bundle exec middleman build --clean --parallel --verbose

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
deploy:
  type: deploy
  environment: production
  script:
  - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
  - echo "${SSH_HOST_KEY}" >  "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --chown=asiwww:asiwww -e 'ssh -i id_rsa' build/ asiwww@tramwaj.asi.wroclaw.pl:fcgi/asi.wroclaw.pl
